use crate::error::Result;

use super::{PatternRule, parse_rule};

const EMBEDDED_RULES: &[(&str, &str)] = &[
    // -- TypeScript / JavaScript --
    (
        "role-check-conditional",
        include_str!("../../rules/typescript/role-check-conditional.toml"),
    ),
    (
        "role-includes-check",
        include_str!("../../rules/typescript/role-includes-check.toml"),
    ),
    (
        "identifier-includes-check",
        include_str!("../../rules/typescript/identifier-includes-check.toml"),
    ),
    (
        "has-role-call",
        include_str!("../../rules/typescript/has-role-call.toml"),
    ),
    (
        "express-auth-middleware",
        include_str!("../../rules/typescript/express-auth-middleware.toml"),
    ),
    (
        "express-route-middleware",
        include_str!("../../rules/typescript/express-route-middleware.toml"),
    ),
    (
        "nestjs-use-guards",
        include_str!("../../rules/typescript/nestjs-use-guards.toml"),
    ),
    (
        "trpc-procedure",
        include_str!("../../rules/typescript/trpc-procedure.toml"),
    ),
    (
        "nestjs-roles-decorator",
        include_str!("../../rules/typescript/nestjs-roles-decorator.toml"),
    ),
    (
        "authorize-function-call",
        include_str!("../../rules/typescript/authorize-function-call.toml"),
    ),
    (
        "permission-check-call",
        include_str!("../../rules/typescript/permission-check-call.toml"),
    ),
    (
        "chained-permission-call",
        include_str!("../../rules/typescript/chained-permission-call.toml"),
    ),
    (
        "membership-check-call",
        include_str!("../../rules/typescript/membership-check-call.toml"),
    ),
    (
        "session-auth-check",
        include_str!("../../rules/typescript/session-auth-check.toml"),
    ),
    (
        "jwt-verify-decode",
        include_str!("../../rules/typescript/jwt-verify-decode.toml"),
    ),
    (
        "jwt-sign-issue",
        include_str!("../../rules/typescript/jwt-sign-issue.toml"),
    ),
    (
        "ownership-check",
        include_str!("../../rules/typescript/ownership-check.toml"),
    ),
    (
        "feature-gate-check",
        include_str!("../../rules/typescript/feature-gate-check.toml"),
    ),
    (
        "ts-aws-verified-permissions",
        include_str!("../../rules/typescript/aws-verified-permissions.toml"),
    ),
    (
        "ts-cedar-express-middleware",
        include_str!("../../rules/typescript/cedar-express-middleware.toml"),
    ),
    // -- Java --
    (
        "java-spring-preauthorize",
        include_str!("../../rules/java/spring-preauthorize.toml"),
    ),
    (
        "java-spring-secured",
        include_str!("../../rules/java/spring-secured.toml"),
    ),
    (
        "java-roles-allowed",
        include_str!("../../rules/java/spring-roles-allowed.toml"),
    ),
    (
        "java-roles-allowed-array",
        include_str!("../../rules/java/spring-roles-allowed-array.toml"),
    ),
    (
        "java-authorized-annotation",
        include_str!("../../rules/java/authorized-annotation.toml"),
    ),
    (
        "java-spring-permit-all",
        include_str!("../../rules/java/spring-permit-all.toml"),
    ),
    (
        "java-is-user-in-role",
        include_str!("../../rules/java/is-user-in-role.toml"),
    ),
    (
        "java-has-role-call",
        include_str!("../../rules/java/has-role-call.toml"),
    ),
    (
        "java-shiro-requires-permissions",
        include_str!("../../rules/java/shiro-requires-permissions.toml"),
    ),
    (
        "java-shiro-requires-roles",
        include_str!("../../rules/java/shiro-requires-roles.toml"),
    ),
    (
        "java-shiro-requires-roles-array",
        include_str!("../../rules/java/shiro-requires-roles-array.toml"),
    ),
    (
        "java-shiro-requires-authentication",
        include_str!("../../rules/java/shiro-requires-authentication.toml"),
    ),
    (
        "java-shiro-is-permitted",
        include_str!("../../rules/java/shiro-is-permitted.toml"),
    ),
    (
        "java-role-equals-check",
        include_str!("../../rules/java/role-equals-check.toml"),
    ),
    (
        "java-ownership-check",
        include_str!("../../rules/java/ownership-check.toml"),
    ),
    (
        "java-http-security-authorize",
        include_str!("../../rules/java/http-security-authorize.toml"),
    ),
    (
        "java-authenticated-check",
        include_str!("../../rules/java/authenticated-check.toml"),
    ),
    (
        "java-access-decision-voter",
        include_str!("../../rules/java/access-decision-voter.toml"),
    ),
    (
        "java-security-interface-impl",
        include_str!("../../rules/java/security-interface-impl.toml"),
    ),
    (
        "java-feature-gate-check",
        include_str!("../../rules/java/feature-gate-check.toml"),
    ),
    (
        "java-custom-authz-call",
        include_str!("../../rules/java/custom-authz-call.toml"),
    ),
    (
        "java-cedar-eval",
        include_str!("../../rules/java/cedar-eval.toml"),
    ),
    (
        "java-aws-verified-permissions",
        include_str!("../../rules/java/aws-verified-permissions.toml"),
    ),
    (
        "java-jaxrs-endpoint",
        include_str!("../../rules/java/jaxrs-endpoint.toml"),
    ),
    // -- Python --
    (
        "py-django-permission-required",
        include_str!("../../rules/python/django-permission-required.toml"),
    ),
    (
        "py-login-required-decorator",
        include_str!("../../rules/python/login-required-decorator.toml"),
    ),
    (
        "py-require-decorator",
        include_str!("../../rules/python/require-decorator.toml"),
    ),
    (
        "py-django-user-passes-test",
        include_str!("../../rules/python/django-user-passes-test.toml"),
    ),
    (
        "py-has-perm-call",
        include_str!("../../rules/python/has-perm-call.toml"),
    ),
    (
        "py-fastapi-depends",
        include_str!("../../rules/python/fastapi-depends.toml"),
    ),
    (
        "py-role-check-conditional",
        include_str!("../../rules/python/role-check-conditional.toml"),
    ),
    (
        "py-has-role-call",
        include_str!("../../rules/python/has-role-call.toml"),
    ),
    (
        "py-permission-check-call",
        include_str!("../../rules/python/permission-check-call.toml"),
    ),
    (
        "py-check-helper-call",
        include_str!("../../rules/python/check-helper-call.toml"),
    ),
    (
        "py-ownership-check",
        include_str!("../../rules/python/ownership-check.toml"),
    ),
    (
        "py-feature-gate-check",
        include_str!("../../rules/python/feature-gate-check.toml"),
    ),
    (
        "py-aws-verified-permissions",
        include_str!("../../rules/python/aws-verified-permissions.toml"),
    ),
    // -- Go --
    (
        "go-has-role-call",
        include_str!("../../rules/go/has-role-call.toml"),
    ),
    (
        "go-permission-check-call",
        include_str!("../../rules/go/permission-check-call.toml"),
    ),
    (
        "go-permission-predicate-call",
        include_str!("../../rules/go/permission-predicate-call.toml"),
    ),
    (
        "go-role-check-conditional",
        include_str!("../../rules/go/role-check-conditional.toml"),
    ),
    (
        "go-ownership-check",
        include_str!("../../rules/go/ownership-check.toml"),
    ),
    (
        "go-casbin-enforce",
        include_str!("../../rules/go/casbin-enforce.toml"),
    ),
    (
        "go-feature-gate-check",
        include_str!("../../rules/go/feature-gate-check.toml"),
    ),
    (
        "go-gin-auth-middleware",
        include_str!("../../rules/go/gin-auth-middleware.toml"),
    ),
    (
        "go-opa-rego-eval",
        include_str!("../../rules/go/opa-rego-eval.toml"),
    ),
    (
        "go-cedar-eval",
        include_str!("../../rules/go/cedar-eval.toml"),
    ),
    (
        "go-aws-verified-permissions",
        include_str!("../../rules/go/aws-verified-permissions.toml"),
    ),
    (
        "go-access-descriptor-builder",
        include_str!("../../rules/go/access-descriptor-builder.toml"),
    ),
    // -- C# / ASP.NET Core --
    (
        "csharp-aspnet-authorize-attribute",
        include_str!("../../rules/csharp/aspnet-authorize-attribute.toml"),
    ),
    (
        "csharp-aspnet-authorize-roles",
        include_str!("../../rules/csharp/aspnet-authorize-roles.toml"),
    ),
    (
        "csharp-aspnet-authorize-policy",
        include_str!("../../rules/csharp/aspnet-authorize-policy.toml"),
    ),
    (
        "csharp-aspnet-authorize-policy-shorthand",
        include_str!("../../rules/csharp/aspnet-authorize-policy-shorthand.toml"),
    ),
    (
        "csharp-aspnet-allow-anonymous",
        include_str!("../../rules/csharp/aspnet-allow-anonymous.toml"),
    ),
    (
        "csharp-aspnet-require-authorization",
        include_str!("../../rules/csharp/aspnet-require-authorization.toml"),
    ),
    (
        "csharp-aspnet-endpoint-allow-anonymous",
        include_str!("../../rules/csharp/aspnet-endpoint-allow-anonymous.toml"),
    ),
    (
        "csharp-is-in-role-call",
        include_str!("../../rules/csharp/is-in-role-call.toml"),
    ),
    (
        "csharp-has-claim-call",
        include_str!("../../rules/csharp/has-claim-call.toml"),
    ),
    (
        "csharp-authorization-service-authorize-async",
        include_str!("../../rules/csharp/authorization-service-authorize-async.toml"),
    ),
    (
        "csharp-aws-verified-permissions",
        include_str!("../../rules/csharp/aws-verified-permissions.toml"),
    ),
    // -- Kotlin --
    (
        "kotlin-spring-preauthorize",
        include_str!("../../rules/kotlin/spring-preauthorize.toml"),
    ),
    (
        "kotlin-spring-secured",
        include_str!("../../rules/kotlin/spring-secured.toml"),
    ),
    (
        "kotlin-roles-allowed",
        include_str!("../../rules/kotlin/roles-allowed.toml"),
    ),
    (
        "kotlin-has-role-call",
        include_str!("../../rules/kotlin/has-role-call.toml"),
    ),
    (
        "kotlin-role-equals-check",
        include_str!("../../rules/kotlin/role-equals-check.toml"),
    ),
    (
        "kotlin-role-collection-contains",
        include_str!("../../rules/kotlin/role-collection-contains.toml"),
    ),
    (
        "kotlin-ktor-authenticate-block",
        include_str!("../../rules/kotlin/ktor-authenticate-block.toml"),
    ),
    (
        "kotlin-ktor-install-authentication",
        include_str!("../../rules/kotlin/ktor-install-authentication.toml"),
    ),
    // -- Ruby --
    (
        "ruby-pundit-authorize",
        include_str!("../../rules/ruby/pundit-authorize.toml"),
    ),
    (
        "ruby-pundit-policy-method",
        include_str!("../../rules/ruby/pundit-policy-method.toml"),
    ),
    (
        "ruby-pundit-policy-class",
        include_str!("../../rules/ruby/pundit-policy-class.toml"),
    ),
    (
        "ruby-cancancan-can-declaration",
        include_str!("../../rules/ruby/cancancan-can-declaration.toml"),
    ),
    (
        "ruby-cancancan-can-check",
        include_str!("../../rules/ruby/cancancan-can-check.toml"),
    ),
    (
        "ruby-rails-before-action-filter",
        include_str!("../../rules/ruby/rails-before-action-filter.toml"),
    ),
    (
        "ruby-role-equals-check",
        include_str!("../../rules/ruby/role-equals-check.toml"),
    ),
    (
        "ruby-role-collection-include",
        include_str!("../../rules/ruby/role-collection-include.toml"),
    ),
    (
        "ruby-current-user-role-predicate",
        include_str!("../../rules/ruby/current-user-role-predicate.toml"),
    ),
    // -- PHP --
    (
        "php-laravel-gate-allows-denies",
        include_str!("../../rules/php/laravel-gate-allows-denies.toml"),
    ),
    (
        "php-laravel-gate-define",
        include_str!("../../rules/php/laravel-gate-define.toml"),
    ),
    (
        "php-laravel-authorize-helper",
        include_str!("../../rules/php/laravel-authorize-helper.toml"),
    ),
    (
        "php-laravel-policy-class",
        include_str!("../../rules/php/laravel-policy-class.toml"),
    ),
    (
        "php-laravel-route-middleware",
        include_str!("../../rules/php/laravel-route-middleware.toml"),
    ),
    (
        "php-symfony-voter-class",
        include_str!("../../rules/php/symfony-voter-class.toml"),
    ),
    (
        "php-symfony-is-granted",
        include_str!("../../rules/php/symfony-is-granted.toml"),
    ),
    (
        "php-symfony-is-granted-attribute",
        include_str!("../../rules/php/symfony-is-granted-attribute.toml"),
    ),
    (
        "php-role-equals-check",
        include_str!("../../rules/php/role-equals-check.toml"),
    ),
    (
        "php-in-array-role-check",
        include_str!("../../rules/php/in-array-role-check.toml"),
    ),
    (
        "php-has-role-call",
        include_str!("../../rules/php/has-role-call.toml"),
    ),
];

pub fn load_embedded_rules() -> Result<Vec<PatternRule>> {
    let mut rules = Vec::with_capacity(EMBEDDED_RULES.len());
    for (name, content) in EMBEDDED_RULES {
        rules.push(parse_rule(content, name)?);
    }
    Ok(rules)
}
