use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::types::Finding;

use super::templates;

pub struct RegoFile {
    pub package_name: String,
    pub output_path: PathBuf,
    pub content: String,
    pub finding_count: usize,
}

/// Derive a Rego package name from a source file path and prefix.
/// e.g., "src/api/orders.ts" with prefix "app" → "app.api.orders"
pub fn derive_package_name(file_path: &Path, prefix: &str) -> String {
    let mut stem = file_path.with_extension("");
    // Strip common source prefixes (only if there are remaining components)
    for common in &["src", "lib"] {
        if let Ok(stripped) = stem.strip_prefix(common)
            && !stripped.as_os_str().is_empty()
        {
            stem = stripped.to_path_buf();
            break;
        }
    }

    let path_str = stem.to_string_lossy();
    let sanitized = path_str
        .replace(['/', '\\'], ".")
        .replace('-', "_")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '.' || *c == '_')
        .collect::<String>();

    // Ensure each segment starts with a letter or underscore (Rego identifier rule)
    let fixed = sanitized
        .split('.')
        .map(|seg| {
            if seg.starts_with(|c: char| c.is_ascii_digit()) {
                format!("_{seg}")
            } else {
                seg.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join(".");

    if prefix.is_empty() {
        fixed
    } else if fixed.is_empty() {
        prefix.to_string()
    } else {
        format!("{prefix}.{fixed}")
    }
}

/// Derive the output .rego file path from a source file path.
/// e.g., "src/api/orders.ts" → "<output_dir>/api/orders.rego"
fn derive_output_path(file_path: &Path, output_dir: &Path) -> PathBuf {
    let mut stem = file_path.with_extension("rego");
    for common in &["src", "lib"] {
        if let Ok(stripped) = stem.strip_prefix(common)
            && !stripped.as_os_str().is_empty()
        {
            stem = stripped.to_path_buf();
            break;
        }
    }
    // Keep only Normal components to prevent path traversal
    let safe_stem: PathBuf = stem
        .components()
        .filter(|c| matches!(c, std::path::Component::Normal(_)))
        .collect();
    output_dir.join(safe_stem)
}

/// Group findings by source file and generate RegoFile structs.
pub fn group_findings(
    findings: &[Finding],
    package_prefix: &str,
    output_dir: &Path,
) -> Vec<RegoFile> {
    // Group by source file
    let mut groups: BTreeMap<&Path, Vec<&Finding>> = BTreeMap::new();
    for finding in findings {
        groups.entry(&finding.file).or_default().push(finding);
    }

    groups
        .into_iter()
        .map(|(file_path, file_findings)| {
            let package_name = derive_package_name(file_path, package_prefix);
            let output_path = derive_output_path(file_path, output_dir);
            let content = build_rego_content(&package_name, file_path, &file_findings);
            let finding_count = file_findings.len();

            RegoFile {
                package_name,
                output_path,
                content,
                finding_count,
            }
        })
        .collect()
}

fn build_rego_content(package_name: &str, source_file: &Path, findings: &[&Finding]) -> String {
    let mut lines = Vec::new();

    // Header
    lines.push("# Generated by zift".to_string());
    lines.push(format!("# Source: {}", source_file.display()));
    lines.push(format!("# Findings: {}", findings.len()));
    lines.push(String::new());
    lines.push(format!("package {package_name}"));
    lines.push(String::new());
    lines.push("import rego.v1".to_string());
    lines.push(String::new());

    // Track whether we've emitted a default allow statement
    let mut has_default_allow = false;

    for (i, finding) in findings.iter().enumerate() {
        if i > 0 {
            lines.push(String::new());
        }

        // Finding header comment
        lines.push(format!(
            "# [{}] {}:{} | {} | {}",
            i + 1,
            finding.file.display(),
            finding.line_start,
            finding.category,
            finding.confidence,
        ));

        // Show the original code as a comment
        let first_line = finding.code_snippet.lines().next().unwrap_or("");
        let truncated = if first_line.chars().count() > 80 {
            let s: String = first_line.chars().take(77).collect();
            format!("{s}...")
        } else {
            first_line.to_string()
        };
        lines.push(format!("# Original: {}", truncated.trim()));

        // Get the Rego stub
        let stub = match &finding.rego_stub {
            Some(s) => s.clone(),
            None => templates::generate_default_stub(finding.category, &finding.code_snippet),
        };

        // Apply confidence wrapping
        let wrapped = templates::apply_confidence_wrapping(&stub, finding.confidence);

        // Check if stub contains "default allow" and add it only once
        for line in wrapped.lines() {
            let trimmed = line.trim();
            let is_default_allow = trimmed
                .strip_prefix("default allow")
                .map(|rest| {
                    rest.is_empty()
                        || rest.starts_with(' ')
                        || rest.starts_with('\t')
                        || rest.starts_with(":=")
                        || rest.starts_with('=')
                })
                .unwrap_or(false);
            if is_default_allow {
                if has_default_allow {
                    continue; // skip duplicate default
                }
                has_default_allow = true;
            }
            lines.push(line.to_string());
        }
    }

    lines.push(String::new()); // trailing newline
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::*;

    #[test]
    fn derive_package_simple() {
        let name = derive_package_name(Path::new("src/api/orders.ts"), "app");
        assert_eq!(name, "app.api.orders");
    }

    #[test]
    fn derive_package_nested() {
        let name = derive_package_name(Path::new("src/api/routes/users.ts"), "app.authz");
        assert_eq!(name, "app.authz.api.routes.users");
    }

    #[test]
    fn derive_package_no_src_prefix() {
        let name = derive_package_name(Path::new("controllers/auth.ts"), "app");
        assert_eq!(name, "app.controllers.auth");
    }

    #[test]
    fn derive_package_hyphenated() {
        let name = derive_package_name(Path::new("src/my-service/auth-check.ts"), "app");
        assert_eq!(name, "app.my_service.auth_check");
    }

    #[test]
    fn derive_output_path() {
        let path =
            super::derive_output_path(Path::new("src/api/orders.ts"), Path::new("./policies"));
        assert_eq!(path, PathBuf::from("./policies/api/orders.rego"));
    }

    #[test]
    fn group_findings_single_file() {
        let findings = vec![Finding {
            id: "abc".into(),
            file: PathBuf::from("src/api/orders.ts"),
            line_start: 10,
            line_end: 12,
            code_snippet: r#"authorize(user, "orders:read", resource)"#.into(),
            language: Language::TypeScript,
            category: AuthCategory::Rbac,
            confidence: Confidence::High,
            description: "test".into(),
            pattern_rule: Some("test-rule".into()),
            rego_stub: None,
            pass: ScanPass::Structural,
        }];

        let files = group_findings(&findings, "app", Path::new("./policies"));
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].package_name, "app.api.orders");
        assert!(files[0].content.contains("package app.api.orders"));
        assert!(files[0].content.contains("import rego.v1"));
        assert!(files[0].content.contains("default allow := false"));
    }

    #[test]
    fn group_findings_multiple_files() {
        let findings = vec![
            Finding {
                id: "a".into(),
                file: PathBuf::from("src/api/orders.ts"),
                line_start: 10,
                line_end: 12,
                code_snippet: r#"hasRole("admin")"#.into(),
                language: Language::TypeScript,
                category: AuthCategory::Rbac,
                confidence: Confidence::High,
                description: "test".into(),
                pattern_rule: None,
                rego_stub: None,
                pass: ScanPass::Structural,
            },
            Finding {
                id: "b".into(),
                file: PathBuf::from("src/api/users.ts"),
                line_start: 5,
                line_end: 5,
                code_snippet: "req.isAuthenticated()".into(),
                language: Language::TypeScript,
                category: AuthCategory::Middleware,
                confidence: Confidence::Medium,
                description: "test".into(),
                pattern_rule: None,
                rego_stub: None,
                pass: ScanPass::Structural,
            },
        ];

        let files = group_findings(&findings, "app", Path::new("./policies"));
        assert_eq!(files.len(), 2);
    }
}
