//! Group findings into Cedar policy files. Cedar's file model is flatter
//! than Rego's (no packages, no module hierarchy) — one `.cedar` file per
//! source file is the natural unit, with the `--policy-prefix` becoming a
//! filename prefix instead of a package prefix.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::types::Finding;

use super::templates;

pub struct CedarFile {
    /// A human-friendly identifier for the file (used in CLI output).
    /// Cedar has no `package` keyword, so this is purely informational —
    /// it does NOT appear in the file body.
    pub label: String,
    pub output_path: PathBuf,
    pub content: String,
    pub finding_count: usize,
}

/// Derive the output `.cedar` file path. Mirrors
/// [`crate::rego::grouping::derive_output_path`] but with a `.cedar`
/// extension and a flat `policy_prefix` filename prefix instead of nested
/// packages.
fn derive_output_path(file_path: &Path, output_dir: &Path, policy_prefix: &str) -> PathBuf {
    let mut stem = file_path.with_extension("cedar");
    for common in &["src", "lib"] {
        if let Ok(stripped) = stem.strip_prefix(common)
            && !stripped.as_os_str().is_empty()
        {
            stem = stripped.to_path_buf();
            break;
        }
    }
    let safe_stem: PathBuf = stem
        .components()
        .filter(|c| matches!(c, std::path::Component::Normal(_)))
        .collect();

    if policy_prefix.is_empty() {
        return output_dir.join(safe_stem);
    }
    // Prepend the prefix as an extra directory segment so multi-tenant
    // outputs stay organized (`policies/cedar/<prefix>/api/orders.cedar`).
    output_dir.join(policy_prefix).join(safe_stem)
}

/// Build a label for CLI output. Cedar has no package concept; we re-use
/// the dotted-path shape from Rego just so the user-facing log lines look
/// consistent across engines.
fn derive_label(file_path: &Path, prefix: &str) -> String {
    let mut stem = file_path.with_extension("");
    for common in &["src", "lib"] {
        if let Ok(stripped) = stem.strip_prefix(common)
            && !stripped.as_os_str().is_empty()
        {
            stem = stripped.to_path_buf();
            break;
        }
    }
    let path_str = stem.to_string_lossy();
    let dotted = path_str.replace(['/', '\\'], ".").replace('-', "_");
    if prefix.is_empty() {
        dotted
    } else if dotted.is_empty() {
        prefix.to_string()
    } else {
        format!("{prefix}.{dotted}")
    }
}

pub fn group_findings(
    findings: &[Finding],
    policy_prefix: &str,
    output_dir: &Path,
) -> Vec<CedarFile> {
    let mut groups: BTreeMap<&Path, Vec<&Finding>> = BTreeMap::new();
    for finding in findings {
        groups.entry(&finding.file).or_default().push(finding);
    }

    groups
        .into_iter()
        .map(|(file_path, file_findings)| {
            let label = derive_label(file_path, policy_prefix);
            let output_path = derive_output_path(file_path, output_dir, policy_prefix);
            let content = build_cedar_content(file_path, &file_findings);
            let finding_count = file_findings.len();

            CedarFile {
                label,
                output_path,
                content,
                finding_count,
            }
        })
        .collect()
}

fn build_cedar_content(source_file: &Path, findings: &[&Finding]) -> String {
    let mut lines = Vec::new();

    lines.push("// Generated by zift".to_string());
    lines.push(format!("// Source: {}", source_file.display()));
    lines.push(format!("// Findings: {}", findings.len()));
    lines.push(String::new());

    for (i, finding) in findings.iter().enumerate() {
        if i > 0 {
            lines.push(String::new());
        }

        lines.push(format!(
            "// [{}] {}:{} | {} | {}",
            i + 1,
            finding.file.display(),
            finding.line_start,
            finding.category,
            finding.confidence,
        ));

        let first_line = finding.code_snippet.lines().next().unwrap_or("");
        let truncated = if first_line.chars().count() > 80 {
            let s: String = first_line.chars().take(77).collect();
            format!("{s}...")
        } else {
            first_line.to_string()
        };
        lines.push(format!("// Original: {}", truncated.trim()));

        let stub = match &finding.cedar_stub {
            Some(s) => s.clone(),
            None => templates::generate_default_stub(finding.category, &finding.code_snippet),
        };
        let wrapped = templates::apply_confidence_wrapping(&stub, finding.confidence);
        for line in wrapped.lines() {
            lines.push(line.to_string());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::*;

    fn finding(file: &str, snippet: &str, category: AuthCategory) -> Finding {
        Finding {
            id: "x".into(),
            file: PathBuf::from(file),
            line_start: 10,
            line_end: 12,
            code_snippet: snippet.into(),
            language: Language::TypeScript,
            category,
            confidence: Confidence::High,
            description: "test".into(),
            pattern_rule: Some("test-rule".into()),
            rego_stub: None,
            cedar_stub: None,
            pass: ScanPass::Structural,
            surface: Surface::Backend,
        }
    }

    #[test]
    fn output_path_with_prefix() {
        let p = derive_output_path(
            Path::new("src/api/orders.ts"),
            Path::new("./policies"),
            "app",
        );
        assert_eq!(p, PathBuf::from("./policies/app/api/orders.cedar"));
    }

    #[test]
    fn output_path_without_prefix() {
        let p = derive_output_path(Path::new("src/api/orders.ts"), Path::new("./policies"), "");
        assert_eq!(p, PathBuf::from("./policies/api/orders.cedar"));
    }

    #[test]
    fn group_findings_single_file_emits_permit() {
        let findings = vec![finding(
            "src/api/orders.ts",
            r#"if (user.role === "admin") {}"#,
            AuthCategory::Rbac,
        )];
        let files = group_findings(&findings, "app", Path::new("./policies"));
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("permit"));
        assert!(files[0].content.contains("// Generated by zift"));
        assert!(files[0].content.contains("admin"));
    }

    #[test]
    fn group_findings_multiple_files() {
        let findings = vec![
            finding("src/a.ts", r#"hasRole("admin")"#, AuthCategory::Rbac),
            finding(
                "src/b.ts",
                "req.isAuthenticated()",
                AuthCategory::Middleware,
            ),
        ];
        let files = group_findings(&findings, "app", Path::new("./policies"));
        assert_eq!(files.len(), 2);
    }
}
